target :Tasks do
  platform :ios, '16.0'
  use_frameworks!
    pod 'MultiPlatformLibrary', :path => '../shared'
    pod 'FirebaseCore'
    pod 'FirebaseAnalytics'
    pod 'FirebaseMessaging'
    pod 'FirebaseCrashlytics'
end
