name: KMMBridge Publish Release
on: workflow_dispatch
permissions:
  contents: write
  packages: write

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@latest
    with:
      jvmVersion: '17'